# ==========================================
# ORIS - CLUSTER CONFIGURATION / PIPELINE
# ==========================================

# 🖥️ CLUSTER (Slurm)
[slurm]
partition           = "CPUQ"          # Cluster queue
account             = "viviamsb"      # Project (if applies)
time                = "24:00:00"        # Time limit ⏳

nodes               = 18                # Number of nodes 🧩
ntasks_per_node     = 14                # MPI tasks per node 🚀

output              = "oris_%j.out"    # Standard log 📄
error               = "oris_%j.err"    # Error log ❗
auto_submit         = true              # Automatic sbatch launch 🧚

# 🧬 ENVIRONMENT
[env]
preamble = """
module load intel/2024a
module load SciPy-bundle/2024.05-gfbf-2024a
module load Python/3.12.3-GCCcore-13.3.0
"""

# 🧠 ORIS configuration
[oris]
default_sampling = 10                       # When no --sampling 🧮
media_targets = ["EGFR", "IGF1R", "MET"]    # Media nodes 🌐
timeout_sampling = 300                      # Sampling threshold (seconds) ⏱️
timeout_paths = 600                         # CountPaths threshold (seconds) ⏱️
